Post messages in groups
opendatacube/odc-tools pull request #210
Opened 2021-06-04 03:20 UTC by alexgleith

* Should make re-driving queues faster
* Tests are only sort of sensible, I think `moto` does strange things when working with fake queues

2021-06-04 05:19 UTC, Kirill888 approved these changes

2021-06-10 00:27 UTC, Kirill888 commented
@alexgleith can you tweak the test settings to not timeout or disable dead-letter test unless somehow requested to run it, waiting 1 minute in a single test for messages to end up in dead letter queue is too much.

2021-06-10 00:27 UTC, Kirill888 requested changes
tests need tweaking to not timeout

2021-06-10 02:29 UTC, alexgleith commented
Yeah, I know the tests aren't working right.

I need some time to work out how Moto is actually working here. It's an odd use case and hard to test with the mocked environment!

Leave it with me.

2021-06-25 02:11 UTC, Kirill888 approved these changes

2021-06-25 02:29 UTC, merged