add thread pool to dump_to_odc
opendatacube/odc-tools pull request #247
Opened 2021-07-08 06:03 UTC by carioca-au

2021-07-09 00:15 UTC, alexgleith requested changes

2021-07-09 00:15 UTC, alexgleith commented on apps/dc_tools/odc/apps/dc_tools/s3_to_dc.py
> +@click.option(
Perhaps we make this configurable for n-threads?

2021-07-09 00:15 UTC, alexgleith commented on apps/dc_tools/odc/apps/dc_tools/s3_to_dc.py
> +        ]
Does this load everything into a list first? Because I think it will be slow.

Everything else is a generator, which is a streaming flow of URIs then YAML docs off S3.

2021-07-09 00:15 UTC, alexgleith commented on apps/dc_tools/odc/apps/dc_tools/s3_to_dc.py
> +        ]
Can we do a functools function to handle the arguments instead?

2021-07-09 00:21 UTC, carioca-au commented on apps/dc_tools/odc/apps/dc_tools/s3_to_dc.py
> +@click.option(
Easy

2021-07-12 02:39 UTC, alexgleith commented on apps/dc_tools/odc/apps/dc_tools/s3_to_dc.py
> +@click.option('--n-threads', default=100, help='Needed when using multithreading to perform better')
Does the default mean it's always on? Default should be `None` or `0`, I think.

2021-07-15 04:29 UTC, closed without merging