Improve Developer Testing Experience
opendatacube/odc-tools pull request #524
Opened 2022-11-14 05:19 UTC by omad

# Background
See #521 

# Changes in this PR
- Add [pytest fixtures](https://docs.pytest.org/en/6.2.x/fixture.html) which automatically start PostgreSQL and provision an ODC Database with Metadata Types and Products. This is only necessary in the `odc.apps` tests.
- Use [moto](http://docs.getmoto.org/en/latest/) to mock AWS services instead of relying on external S3 objects, which have recently changed and broken tests.
- Remove [pytest-depends](https://pypi.org/project/pytest-depends/) and replace with [pytest fixtures](https://docs.pytest.org/en/6.2.x/fixture.html) , making it possible to run any test individually.
- Unfortunately: Lots of linting and formatting related fixes

2022-11-14 22:44 UTC, omad commented
As described in #526 I'm going to fix the outstanding linting issues caught by pre-commit.ci in a follow up PR.

2022-11-15 01:21 UTC, Ariana-B commented on apps/dc_tools/odc/apps/dc_tools/utils.py
> +                    dc.index.datasets.update_flag(ds, updates_allowed=updates)
accidental replace?

2022-11-15 01:26 UTC, Ariana-B commented on apps/dc_tools/tests/conftest.py
>  @pytest.fixture
Should this fixture also be updated?

2022-11-15 01:50 UTC, Ariana-B commented on libs/cloud/odc/aws/_find.py
> +            raise ValueError("Bad query: {url_query}")
Missing an `f` in front

2022-11-15 01:55 UTC, Ariana-B requested changes, later dismissed
Let's either determine what's causing the pylint warning with `update` and `update-if-exists` and revert the name change, or update the `cli` parameters in each file accordingly

2022-11-15 02:13 UTC, Ariana-B reviewed
Other than the couple minor comments, looks good!

2022-11-15 06:32 UTC, omad commented on apps/dc_tools/tests/conftest.py
>  @pytest.fixture
Yep, thanks!

2022-11-15 06:32 UTC, omad commented
Thanks for catching those Ariana!

2022-11-15 06:32 UTC, merged